language: haskell
ghc: 7.8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libsnappy-dev
  - wget https://leveldb.googlecode.com/files/leveldb-1.9.0.tar.gz
  - tar -xzf leveldb-1.9.0.tar.gz
  - cd leveldb-1.9.0
  - make
  - sudo mv libleveldb.* /usr/local/lib
  - cd include
  - sudo cp -R leveldb /usr/local/include
  - sudo ldconfig
  - cd ../..
  - cabal install hpc-coveralls

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test

after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls test-horse