language: haskell
ghc: 7.8
script:
  - cabal configure --enable-tests && cabal build && cabal test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libsnappy-dev
  - wget https://leveldb.googlecode.com/files/leveldb-1.9.0.tar.gz
  - tar -xzf leveldb-1.9.0.tar.gz
  - cd leveldb-1.9.0
  - make
  - sudo mv libleveldb.* /usr/local/lib
  - cd include
  - sudo cp -R leveldb /usr/local/include
  - sudo ldconfig
  - cd ../..